DEV-256 Fixed SignalR connection mapping bug + increased timeouts (#12)

diff --git a/package/debian/DEBIAN/postinst b/package/debian/DEBIAN/postinst
--- a/package/debian/DEBIAN/postinst
+++ b/package/debian/DEBIAN/postinst
@@ -1,31 +1,71 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 
-if [ "$1" = "configure" ]
-then
-  groupadd -r thingsplex || true
-  groupadd -r easee || true
+add_user_and_group() {
+	if ! getent group thingsplex >/dev/null
+	then
+		echo -n "Adding group thingsplex..."
+		addgroup --quiet \
+			--system \
+			thingsplex 2>/dev/null || true
+		echo "...OK"
+	fi
 
-  useradd -r -N -M -d / -s /bin/false -g thingsplex easee || true
+	if ! getent passwd easee >/dev/null
+	then
+		echo -n "Adding user easee..."
+		adduser --quiet \
+			--system \
+			--ingroup thingsplex \
+			--no-create-home \
+			--disabled-password \
+			easee 2>/dev/null || true
+		echo "...OK"
+	fi
+}
 
-  chown -R easee:thingsplex /var/log/thingsplex/easee/ || true
-  chown -R easee:easee /opt/thingsplex/easee/ || true
-fi
+create_dirs_and_files() {
+	echo -n "Creating required directories and files..."
+	mkdir -p /opt/thingsplex/easee/data
+	mkdir -p /var/log/thingsplex/easee
+	touch /var/log/thingsplex/easee/easee.log
+	echo "...OK"
+}
 
-deb-systemd-helper unmask easee.service >/dev/null || true
+set_ownership() {
+	echo -n "Set proper ownership and rights for files..."
+	chown -R easee:thingsplex /opt/thingsplex/easee || true
+	chown -R easee:thingsplex /var/log/thingsplex/easee || true
+	chmod 644 /opt/thingsplex/easee/defaults/* || true
+	chmod 644 /opt/thingsplex/easee/VERSION
+	chmod 644 /var/log/thingsplex/easee/* || true
+	echo "...OK"
+}
 
-if deb-systemd-helper --quiet was-enabled easee.service; then
-  systemctl enable easee.service || true
-else
-  deb-systemd-helper update-state easee.service >/dev/null || true
-fi
+configure_service() {
+		echo -n "Configuring service..."
+		systemctl enable easee.service > /dev/null || true
+		systemctl --system daemon-reload >/dev/null || true
+		systemctl start easee.service > /dev/null || true
 
-if [ -d /run/systemd/system ]; then
-  systemctl --system daemon-reload >/dev/null || true
+		echo "...OK"
+}
 
-  if [ -n "$2" ]; then
-    deb-systemd-invoke try-restart easee.service >/dev/null || true
-  else
-    deb-systemd-invoke start easee.service >/dev/null || true
-  fi
-fi
+case "$1" in
+	configure)
+		add_user_and_group
+		create_dirs_and_files
+		set_ownership
+		configure_service
+	;;
+
+	abort-upgrade|abort-remove|abort-deconfigure)
+	;;
+
+	*)
+		echo "postinst called with an unknown argument \`$1'" >&2
+		exit 1
+	;;
+esac
+
+exit 0
